config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  # resources :collaborators
  root 'welcome#index'
  
  
  resources :wikis do
  resources :collaborators, only: [:new, :create, :destroy]
  end
  
  resources :charges, only: [:new, :create, :destroy]
  devise_for :users
  resources :search
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :user
    has_many :wikis
    
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
   before_save { self.email = email.downcase if email.present? }
   after_initialize { self.role ||= :standard }

   validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

  enum role: [:standard, :admin, :premium]

end

# wikis belongs to user

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  after_initialize { self.private ||= false }
  

end

# user has many wikis

app/models/wikiOG.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  after_initialize { self.private ||= false }
  

end

# user has many wikis

app/controllers/amount_controller.rb
class Amount
    def default
        @amount = 15_00
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery  with: :exception
	  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
      
   customer = Stripe::Customer.create(
      email: current_user.email,
      source: params[:stripeToken]
    )
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 1500,
     description: "Premium Membership - #{current_user.email}",
     currency: 'usd'
   )
    
    current_user.update_attributes(role: 'premium')
 
   flash[:notice] = "You've been upgraded to premium, #{current_user.email}!"
   redirect_to root_path # or wherever
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.email}",
     amount: 1500
   }
#   binding.pry
  end
  
  def destroy
    #   binding.pry
   current_user.update_attributes(role: 'standard')

    # Make all the wikis belonging to the current user public
#   TODO: Fix this
#   wikis = Wiki.all
   wikis = current_user.wikis
   wikis.each do |w|
     w.update(private: false)
   end
   
   flash[:notice] = "You're no longer subscribed as  premium user, #{current_user.email} (CHUM!)"
   redirect_to root_path    
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    
  before_action :require_sign_in
  before_action :authorize_user

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user.User.where(email: params[:user])
    collaborator = @wiki.collaborators.build(user_id: @user.id)

    if collaborator.save
      flash[:notice] = "Collaborator has been saved!"
    else
      flash.now[:alert] = "We couldn't save your collaborators, try adding them again."
    end

    redirect_to wikis_path
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed successfully."
      redirect_to wikis_path
    else
      flash[:alert] = "There was an error deleting the collaborators."
      render :show
    end
  end

  private

  def authorize_user
    wiki = Wiki.find(params[:id])
    unless current_user == wiki.user && current_user.role == 'premium' || current_user.role == 'admin'
      flash[:alert] = "Upgrade to Premium to add Collaborators!"
      redirect_to root_path
    end
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    
    def search
        
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
    
    def new
        @wiki = Wiki.new
    end
    
    def index
        @wiki = Wiki.all
    end
    
    def create
     @wiki = Wiki.new
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]

     if @wiki.save
       flash[:notice] = "Your new Bloci was saved"
       redirect_to @wiki
     else
       flash.now[:alert] = "Error! Bloci was not saved, please try again"
       render :new
     end
    end
    
    def show
        @wiki = Wiki.find(params[:id])
    end
    
    def edit
        @wiki = Wiki.find(params[:id])
    end
    
    def update
     @wiki = Wiki.find(params[:id])
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]

     if @wiki.save
       flash[:notice] = "Your updates have been noted!"
       redirect_to @wiki
     else
       flash.now[:alert] = "Error! Bloci was not updated, please try again"
       render :new
     end
    end
    
    def destroy
      @wiki = Wiki.find(params[:id])
      if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" has been deleted. I hope you're proud of yourself!"
      redirect_to root_path
      else
      flash[:alert] = "Error! This Bloci remains! Maybe you should think again about deleting someone else's hard work!"
      render :show
      end
    end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    skip_before_action :authenticate_user!
    # wikis controller has user assigned and privacy assigned
    def new
        @user = current_user
        @wiki = Wiki.new
    end
    
    def index
        @user = current_user
        @wiki = policy_scope(Wiki)
        # @wiki = Wiki.all
        # @wiki = Wiki.order("published_at DESC")
    end
    
    def create
     @wiki = Wiki.new
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]
    #  @wiki.public = params[:wiki][:public]
     @wiki.private = params[:wiki][:private]
     @wiki.user = current_user

     if @wiki.save
       flash[:notice] = "Your new Chomp was saved"
       redirect_to @wiki
     else
       flash.now[:alert] = "Error! Your Chomp jumped back into the ocean, please try again"
       render :new
     end
    end
    
    def show
        @wiki = Wiki.find(params[:id])
    end
    
    def edit
        @wiki = Wiki.find(params[:id])
    end
    
    def update
     @wiki = Wiki.find(params[:id])
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]
     @wiki.private = params[:wiki][:private]
    #  @wiki.public = params[:wiki][:public]


     if @wiki.save
       flash[:notice] = "Your updates have been noted!"
       redirect_to @wiki
     else
       flash.now[:alert] = "Error! Chomp was not updated, please try again"
       render :new
     end
    end
    
    def destroy
      @user = current_user
      @wiki = Wiki.find(params[:id])
      if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" has been deleted. I hope you're proud of yourself!"
      redirect_to root_path
      else
      flash[:alert] = "Error! This Chomp remains! Maybe you should think again about deleting someone else's hard work!"
      render :show
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
   end
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/charges/edit.html.erb
<h1>Are you sure you want to cancel your membership?</h1>





 <div class = "bottom-bar">
  <center>
   Contact | About us | Upgrade
   <br>
   <br>
   Donate | Help | Etc
   <br>
   <br>
   Search <input type="text" name="search"> <button>Submit</button>
  </center>
 </div>

app/views/charges/new.html.erb
 <div class ="charges-form2">
  
  <div class="table-responsive pull-right col-md-3">
  <table class="table">
   <h2 class = "CHANGE">What are roles anyway?</h2>
    <p><strong>Standard:</strong> Everyone starts out as a tiny guppy, but you have the chance to upgrade to Great-White PREMIUM status TODAY! As a standard member you have access to all public wikis, however, no private ones.</p>
    <p><strong>Premium:</strong> Upgrade today and start your PREMIUM membership as an exclusive Great-White member! Premium users get to make, edit, and utilize private wikis! Keep your secrets among friends, and away from the peasants!</p>
  </table>
</div>
<% if current_user.role == 'standard' %>
<div class = "charges-form">
 <div class="table-responsive">
  <table class="table">
   <h2 class = "CHANGE">What you get when you upgrade!</h2>
    <li>
     <ul>Exclusive access to private wikis</ul>
     <ul>Prestige knowing you're the bougiest of members</ul>
     <ul>A wonderful sense of superiority!</ul>
    </li>
  </table>
</div>

 
  <%= form_tag charges_path do %>
   <h4>Upgrade to Premium!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" >
    // Stripe.setPublishableKey('pk_test_blrYSq2P2hRvHT8CpPRQhThw');
   </script>
  <% end %>
 
  <% elsif current_user.role == 'premium' %>
 <div class = "pull-right"><%= image_tag("chum_downgrade_placeholder.png", :alt => "become chum") %>
 </div>
 <div class="table-responsive charges-form">
  <table class="table">
   <h2 class = "CHANGE">Not happy with your subscription?</h2>
    <p>
     Just be aware if you choose to downgrade all your private wikis become public!
    </p>
  </table>
   <%= form_tag charges_path do %>
   <h4>Downgrade to Standard-Chum</h4>
   <button class = "stripe-button">
    <%= link_to "Downgrade Account", @charge, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade your account? Downgrading your account will result in your private Chomps becoming public.'} %>
    </button>
  <% end %>
</div>
</div>

<% end %>
</div>
<div class = "bottom-bar">
  <center>
   Contact | About us | Upgrade
   <br>
   <br>
   Donate | Help | Etc
   <br>
   <br>
   Search <input type="text" name="search"> <button>Submit</button>
  </center>
 </div>

app/views/collaborators/_form.html.erb
<div class = "row">
    <div class="col-md-4">
        <%= form_for [@wiki, Collaborator.new] do |collab| %>
            <div class="form-group">
              <h4>Add Collaborators</h4>
              <p><strong>Enter the email of the person you want to collab with!</strong></p>
              <%= collab.label :user, class: 'sr-only' %>
              <%= collab.text_field :user, class: 'form-control', placeholder: "Collaborator's email" %>
            </div>
            <div class="form-group">
              <%= collab.submit "Add 'em!", class:'btn btn-success' %>
            </div>
      <% end %>
   </div>

app/views/collaborators/new.html.erb
<div class="content">
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Norican" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
 <div class = "unique-nav">
 <ul class="nav nav-tabs">
       <li class = "main-links"><%= link_to "Home", root_path %></li>
       <li class = "main-links"><%= link_to "Chomps", wikis_path %></li>
    <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
 
 <div class = "nav nav-tabs pull-right">
 <% if user_signed_in? && current_user.role == 'standard' %>
   <li class = "main-links"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
   <li class = "main-links"><%= link_to 'Upgrade to Premium', new_charge_path, :class => 'navbar-link' %></li>
   <li class = "main-links"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
 <div class = "user-info">Signed in as: <strong><%= current_user.email %></strong> | Membership: <strong><%= current_user.role %></strong></div>
 <% elsif user_signed_in? && current_user.role == 'premium' %>
  <li class = "main-links"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
  <li class = "main-links"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
  <li class = "main-links"><%= link_to 'End Subscription', new_charge_path, :class => 'navbar-link' %></li>
 <div class = "user-info">Signed in as: <strong><%= current_user.email %></strong> | Membership: <strong><%= current_user.role %></strong></div>
  </div>
  </div>
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
 </div>
 <!-- issue here - links dont want to work -->
 <div class="site-body">
     <ul class="tabs">
       
       
     </ul>
   </div>
   </div>
    <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
     
     <%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<br>
<br>
<br>
<br>
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class = "bg-test">
<div class = "test">


 <center><div class="index-view">
  <div class = "index-header">
   <h1 class = "fancy"><%= image_tag("chomptionary2.png", :alt => "Welcome to the Chomptionary!") %></h1>
 </div>
 </div></center>
  <div class = "row">
 <div class = "chat col-md-2">
  Chat Box
 </div>
 </div>
 

  <div class="row spacing">
   <p>
       <div class = "col-md-2">PLACEHOLDER</div>
   </p>
   <p>
       <div class = "col-md-2">PLACEHOLDER</div>
   </p>
  </div>

<center><div class ="diamonds dark1-text"><p><h4 class = "white-font">Hook, line, and sinker - you know you're going to need a bigger boat for all these tips and teeth!</h4></p></div></center>
 
 <div class="row">
   <div class="col-md-4"><div class = "img"><%= image_tag("hamerhead.png", :alt => "Blocipedia") %></div>
     <h2>Hook a Reader</h2>
     <p>Got some great shark facts? Don't keep them to yourself!</p>
   </div>
    <div class="col-md-4"><div class = "img"><%= image_tag("hamerhead.png", :alt => "Blocipedia") %></div>
     <h2>Info at your FIN-gertips</h2>
     <p>Expand your shark-based knowledge!</p>
   </div>
    <div class="col-md-4"><div class = "img"><%= image_tag("hamerhead.png", :alt => "Blocipedia") %></div>
     <h2>Chomp it!</h2>
     <p>Take a bite out of a public file and insert your own knowledge!</p>
   </div>
 </div>
 

 

 
</div>
</div>
 <div class = "bottom-bar-agreeable">
  <center>
   Contact | About us | Upgrade
   <br>
   <br>
   Donate | Help | Etc
   <br>
   <br>
   Search <input type="text" name="search"> <button>Submit</button>
  </center>
 </div>

app/views/welcome/show.html.erb
<br>
<br>
<br>
<br>
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/wikis/_form.html.erb
 <div class="row">
   <div class="col-md-4">
     <p>Need some tips before creating your Chomp?</p>
     <ul>
       <li>Make it relevant!</li>
       <li>Remember to include sources for your information.</li>
       <li>Add pictures, quotes, and personal anecdotes to make your topic super interesting!</li>
     </ul>
   </div>
   <div class="col-md-6">
   <%= form_for @wiki do |wiki| %>

    <div class="form-group">
      <%= wiki.label :title %>
      <%= wiki.text_field :title, class: 'form-control', placeholder: 'Enter CHOMP Title' %>
    </div>
    <div class="form-group">
      <%= wiki.label :body %>
      <%= wiki.text_area :body, class: 'form-control', placeholder: 'Enter your FINtformation' %>
    </div>
    <!--private checkbox here-->
      <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= wiki.label :private, class: 'checkbox' do %>
          <%= wiki.check_box :private %> Private topic
        <% end %>
      </div>
    <%= wiki.submit "Save", class: 'btn btn-success' %>
    <% end %>
    <% end %>
   </div>
 </div>

app/views/wikis/collab.html.erb
<div class = "row">
    <div class="col-md-4">
   <%= form_for @collaborators do |collab| %>

    <div class="form-group">
      <%= collab.text_field :title, class: 'form-control', placeholder: 'Enter CHOMP Title' %>
    </div>
    <%= wiki.submit "Add Collaborator", class: 'btn btn-success' %>
    <% end %>
    <% end %>
   </div>
</div>

app/views/wikis/edit.html.erb
<br>
<br>
<br>
<br>

 <h1>Edit this Bloci</h1>
 <br><h4>Insert your own knowledge, trick college students around the world!</h4>
 
 <div class = "pull-right">
  <table>
    Collaborators:
    <p>
      PLACEHOLDER
    </p>
  </table>
</div>

<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter body" %>
      </div>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private Wiki
        <% end %>
        <br>
      <div class="col-md-3">
      <input type="text" class="form-control" placeholder="Add a Collaborator">
      <!--<button type="submit" class="btn btn-default">Submit</button>-->
      </div>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<div class = "bg-test">
<div class = "test">

<div class="index-view">
  <div class = "index-header">
   <h1 class = "fancy"><center><%= image_tag("chum_downgrade_placeholder.png", :alt => "Blocipedia") %></center></h1>
   <br>
   <br>
   <br>
   <div><center><h4 class = "fancy">placeholder</h4></center></div>
 </div>
 </div>
 
 <!--logic for prem and admin users to view private wikis-->
 
 <% if current_user && current_user.role == 'premium' %>
 <div class="diamonds">
    <h2>Your Private Chomps</h2>
      <% if current_user.wikis.count === 0 %> <!--only this line seems to return-->
      <p>Feel free to take the bait and make a private <%= link_to "Chomp", new_wiki_path %>!</p>
      <% else %> <!--I create wikis with a premium user and they don't show up/appear, and the "feel free to create..." string returns-->
        <% current_user.wikis.each do |wiki| %>
            <% if wiki.private %>
              <p class = "plink"><strong><%= link_to wiki.title, wiki %></strong></p>
            <% end %>
      <% end %>
      <% end %>
      </div>
  <% end %>

  
  <div class = "new-wiki">
  <h3><%= link_to "New", new_wiki_path, class: 'pull-right' %></h3>
  </div>
  
 <table class="row">
<% @wiki.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <!--<h4 class="media-heading">-->
      <div class="col-md-3">
      <h4 class="wiki-title">
         <% if wiki.private != true %>
         <%= link_to wiki.title, wiki %>
         <% end %>
      </h4>
    </div>
  </div>
  </div>
  </table>
<% end %>
</div>
</div>
  
  <div class = "bottom-bar-agreeable">
  <center>
   Contact | About us | Upgrade
   <br>
   <br>
   Donate | Help | Etc
   <br>
   <br>
   Search <input type="text" name="search"> <button>Submit</button>
  </center>
 </div>

app/views/wikis/new.html.erb
<br>
<br>
<br>
<br>

 <h1>Create a Wiki</h1>
 <p><h4>(not to be confused with a wookie!)</h4></p>
<div class="content">
  <%= render 'form' %>
</div>

<div class = "markdown">
  <h3>Markdown Cheat-Sheet!</h3>
  <li>
    <ol><strong>Bold</strong>: ** or __</ol>
    <ol><strikethrough>Delete</strikethrough>: ~~</ol>
    <ol><em>Italic</em>: *</ol>
  </li>
</div>

 <div class = "bottom-bar">
  <center>
   Contact | About us | Upgrade
   <br>
   <br>
   Donate | Help | Etc
   <br>
   <br>
   Search <input type="text" name="search"> <button>Submit</button>
  </center>
 </div>

app/views/wikis/show.html.erb
<br>
<br>
<br>
<br>
<br>

<h1><center><%= @wiki.title %></center></h1>
<p>
  <h4 class = "pull-right"> <%= link_to "Back to Index", wikis_path %> </h4>
</p>
<br>
<br>
<br>
<br>
<br>
 <% if @wiki.private == true %>
 
 <div class = "collaborators">
     <%= render partial: 'collaborators/form', locals: {wiki_id: @wiki.id} %>
      <!--link_to "Add", new_collaborators_path, class: 'pull-right btn-info XSmall' -->
  <table>
   <p>Your Collaborators:</p>
    <% @wiki.collaborators.each do |collaborator| %>
      <p><%= collaborator.user.email %></p>
    <% end %>
    </p>
  </table>
</div>
<% end %>

<center>
<div class="row show-view">
  <div class="col-md-8">
    <h3><%= @wiki.title %></h3>
<p>
  <%= markdown(@wiki.body) %>
</p>
<h4>Published : (fix later)</h4>
    <br>
 <!--%= @wiki.user.email %'s Chomp-->
    </div>
</div>
 <div class = "pull-right">
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure about this?!'} %>
  </div>
</center>

<div class = "markdown">
  <h3>Markdown Cheat-Sheet!</h3>
  <li>
    <ol><strong>Bold</strong>: ** or __</ol>
    <ol><strikethrough>Delete</strikethrough>: ~~</ol>
    <ol><em>Italic</em>: *</ol>
  </li>
</div>

 <div class = "bottom-bar-agreeable">
  <center>
   Contact | About us | Upgrade
   <br>
   <br>
   Donate | Help | Etc
   <br>
   <br>
   Search <input type="text" name="search"> <button>Submit</button>
  </center>
 </div>